f = open('demofile.txt')
print(f.read())
f.close()
f = open('demofile.txt', 'a')
f.write('this has more content now')
f.close()
f = open('demofile.txt')
print(f.read())
f.close()
f = open('demofile.txt','w')
f.write('this content is deleted')
f.close()
f = open('demofile.txt')
print(f.read())
